### ISSUE TITLE
Washing program time remaining

### ISSUE THREAD

**Issue by Ubuntubirdy** [siku2/hass-vzug#36]
So far I have integrated my AdoraWash V2000 with a Restful sensor into HA. Thanks to your integration, I now have a lot more information about my washing machine - thank you!
However, one piece of information is missing: the remaining time of the washing program. I received this from the Restful sensor via "duration.act" and that is one of the most important pieces of information for me.
Would it be possible to include this information in the integration?

Edit: Oh, I just found it: the diagnostic tab...

**Comment by siku2** [comment]
I still think this could be useful as a non-diagnostic sensor as well, no? Or are you fully satisfied with the diagnostic one?

**Comment by Ubuntubirdy** [comment]
Yes, of course! A sensor like this would be great! It's just not as urgent now that I've found it in the diagnostics.
