### ISSUE TITLE
Integration of AdoraDish V2000

### ISSUE THREAD

**Issue by simondaehler** [siku2/hass-vzug#8]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I tried to integrate my AdoraDish V2000 (Actuelly it is branded Fors, but its the same and I use the V-Zug app, which shows it as an AdoraDish V2000).
If I try to integrate the dishwasher, i get the following message:
![Bildschirmfoto vom 2023-08-27 21-25-49](https://github.com/siku2/hass-vzug/assets/48116796/51fd6aed-4616-4cb5-b0b1-39f0c3148993)

### Describe the solution you'd like

I would like to be able to integrate it via the Add-On

### Describe alternatives you've considered

Currently I use the following YAML code:

#Geschirrspühler
  - platform: rest
    resource: http://192.168.1.168/ai?command=getDeviceStatus
    name: 'V-Zug Adoraspulen V2000'
    json_attributes:
      - DeviceName
      - Serial
      - Inactive
      - Status
      - Program
      - ProgramEnd
  - platform: template
    sensors:
      vzug_adoraspuhlen_devicename:
        friendly_name: 'V-ZugAdoraspülen V2000 DeviceName'
        value_template: "{{ state_attr('sensor.v_zug_adoraspulen_v2000', 'DeviceName') }}"
      vzug_adoraspuhlen_serial:
        friendly_name: 'V-Zug Adoraspülen V2000 Serial'
        value_template: "{{ state_attr('sensor.v_zug_adoraspulen_v2000', 'Serial') }}"
      vzug_adoraspuhlen_inactive:
        friendly_name: 'V-Zug Adoraspülen V2000 Inactive'
        value_template: "{{ state_attr('sensor.v_zug_adoraspulen_v2000', 'Inactive') }}"
      vzug_adoraspuhlen_status:
        friendly_name: 'V-Zug Adoraspülen V2000 Status'
        value_template: "{{ state_attr('sensor.v_zug_adoraspulen_v2000', 'Status') }}"
      vzug_adoraspuhlen_program:
        friendly_name: 'V-Zug Adoraspülen V2000 Program'
        value_template: "{{ state_attr('sensor.v_zug_adoraspulen_v2000', 'Program') }}"
      vzug_adoraspuhlen_end:
        friendly_name: 'V-Zug Adoraspülen V2000 End'
        value_template: "{{ state_attr('sensor.v_zug_adoraspulen_v2000', 'ProgramEnd')['End'] }}"
      vzug_adoraspuhlen_endtype:
        friendly_name: 'V-Zug Adoraspülen V2000 End'
        value_template: "{{ state_attr('sensor.v_zug_adoraspulen_v2000', 'ProgramEnd')['EndType'] }}"
    

### Additional context

Here my latest LOG

![Bildschirmfoto vom 2023-08-27 21-30-27](https://github.com/siku2/hass-vzug/assets/48116796/cd86d341-38f5-4c29-8af4-f693297e5399)

**Comment by siku2** [comment]
Are you sure you're running the latest version ([0.3.1](https://github.com/siku2/hass-vzug/releases/tag/0.3.1))? The error in your logs looks exactly like an issue that was fixed in that release.

If you are already on the newest version, please enable debug logging for the integration and post the full logs here, @simondaehler?
